#!/bin/bash

set -eu
topdir=$(dirname $0|xargs realpath)
source "$topdir/configs/settings.sh"

PORT=$1  # Specify port as the first argument

img=yarikoptic-runestone:0.2.0

# NOTE: books must not be symlinked from /srv/ext so also bind mounted

# TODO: make it record started container for the $img and then check/restart
#       instead of running a new one
docker run -it \
  -e DB_PASSWORD=$DB_PASSWORD \
  -p $PORT:8080 \
  -v "$topdir/ext:/srv/ext" \
  -v "$topdir/ext/books:/srv/web2py/applications/runestone/books" \
  $img 
  
# -v "$topdir/../RunestoneServer/docker/entrypoint.sh:/entrypoint.sh" --entrypoint /entrypoint.sh \
